# use Linear regression model

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\HP\Downloads\ML Project - Linear Regression Insurance Prediction.csv")

In [4]:
df.head(1)

age     sex   bmi  children smoker     region    charges
0   19  female  27.9         0    yes  southwest  16884.924

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [9]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [12]:
df["sex"].unique()

array(['female', 'male'], dtype=object)

In [14]:
df["smoker"].unique()

array(['yes', 'no'], dtype=object)

In [11]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [15]:
df["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [28]:
df["region"].unique()

array([3, 2, 1, 0])

In [13]:
df["children"].unique()

array([0, 1, 3, 2, 5, 4], dtype=int64)

In [17]:
df.shape

(1338, 7)

In [25]:
# Encoding

from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()

df[["sex","smoker","region"]]=df[["sex","smoker","region"]].apply(enc.fit_transform)

In [21]:
df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [27]:
df.head(2)

age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [33]:
x=df.drop("charges",axis=1)

In [35]:
y=df["charges"]

In [493]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=15,random_state=21)

In [494]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [495]:
y_pred=model.predict(x_test)

In [496]:
r2=r2_score(y_test,y_pred)

In [497]:
print(r2)

0.7145588621719563


In [498]:
mae=mean_absolute_error(y_test,y_pred)

In [499]:
print(mae)

4018.0943779390923


In [500]:
mse=mean_squared_error(y_test,y_pred)

In [501]:
print(mse)

42162919.970944755


In [502]:
newdata=[[19,0,27.900,0,1,3]]

In [503]:
model.predict(newdata)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([21101.25134704])

In [504]:
df.head(1)

age  sex   bmi  children  smoker  region    charges
0   19    0  27.9         0       1       3  16884.924

# use random forest model 

In [505]:
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn .metrics import r2_score,accuracy_score,mean_absolute_error,mean_squared_error

In [507]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [508]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [509]:
y_pred = rf_model.predict(x_test)

In [510]:
# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [532]:
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R² Score: {r2}")

Mean Absolute Error (MAE): 2533.674643617756
Mean Squared Error (MSE): 21073365.415079337
Root Mean Squared Error (RMSE): 4590.5735387944
R² Score: 0.8642606273649586


In [512]:
cd Download/

[WinError 2] The system cannot find the file specified: 'Download/'
C:\Users\HP\Machine_learning


In [513]:
joblib.dump(rf_model, 'random_forest_model_In.pkl')

['random_forest_model_In.pkl']

In [515]:
rf_model = joblib.load('random_forest_model_In.pkl')

In [523]:
newdata={"age":[19],"sex":[0],"bmi":[27.900],"children":[0],"smoker":[1],"region":[3]}

In [524]:
newdf = pd.DataFrame(newdata)

In [526]:
predicted_price = rf_model.predict(newdf)

In [533]:
predicted_price

array([17198.792596])

In [529]:
print(f"Prediction charges is:${predicted_price[0]:,.2f}")

Prediction charges is:$17,198.79


In [530]:
df.head(1)

age  sex   bmi  children  smoker  region    charges
0   19    0  27.9         0       1       3  16884.924